version: "3.7"

services:

  database:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  display:
    build:
      dockerfile: DockerfileDisplay
      context: .
    expose:
      - "8080"
    volumes:
      - "./display:/display"
      - "./display/dist:/display/dist"
    depends_on:
      - server
    restart: always

  server:
    build:
      dockerfile: DockerfileServer
      context: .
    ports:
      - "8577:8577"
    volumes:
      - "./server:/server"
    depends_on:
      - database
    restart: always

  controller:
    build:
      dockerfile: DockerfileController
      context: .
    volumes:
      - "./controller:/controller"
    depends_on:
      - database
    restart: always
