version: "3.7"

services:

  database:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  server:
    build:
      dockerfile: DockerfileServer
      context: .
    ports:
      - "8577:8577"
    environment:
      REDIS_HOST: "database"
      REDIS_PORT: "6379"
    volumes:
      - "~/rpi-controller/server:/server"
      - "~/rpi-controller/server:/server/server"
      - "~/rpi-controller/database:/server/database"
      - "~/rpi-controller/common:/server/common"
    depends_on:
      - database
    restart: always

  controller:
    build:
      dockerfile: DockerfileController
      context: .
    environment:
      REDIS_HOST: "database"
      REDIS_PORT: "6379"
      LOCAL: "false"
    volumes:
      - "~/rpi-controller/controller:/controller"
      - "~/rpi-controller/controller:/controller/controller"
      - "~/rpi-controller/database:/controller/database"
      - "~/rpi-controller/common:/controller/common"
    depends_on:
      - database
    restart: always
