version: "3.7"

services:

  database:
    image: redis
    command: redis-server --dir ./
    ports:
      - "6379:6379"
    restart: always

  server:
    build:
      dockerfile: DockerfileServer
      context: .
    ports:
      - "8577:8577"
    environment:
      REDIS_HOST: "database"
      REDIS_PORT: "6379"
    volumes:
      - "./server:/server"
      - "./server:/server/server"
      - "./database:/server/database"
    depends_on:
      - database
    restart: always

  controller:
    build:
      dockerfile: DockerfileController
      context: .
    environment:
      REDIS_HOST: "database"
      REDIS_PORT: "6379"
      LOCAL: "true"
    volumes:
      - "./controller:/controller"
      - "./controller:/controller/controller"
      - "./database:/controller/database"
    depends_on:
      - database
    restart: always
