# This script will run the FastAPI server.

# First, let's make sure the venv is active. Double-sourcing the venv isn't a problem,
# so even if you already activated it this won't hurt.
source venv/bin/activate

# Next up, we gotta get some files to serve from the frontend. Let's run that:
# Run our Vue build script
npm run --prefix ../display build 
# Copy all the files generated by the build script to the place where our server expects
cp -R ../display/dist/ ./vue-app

# Finally, run the server.
uvicorn main:app --reload --host localhost --port 8577
